cbv_trees/urls.py
from django.urls import path
from django.views.generic import TemplateView, ListView

from cbv_trees.models import Map
from cbv_trees.views import TreeNodeFormSetView, TreeNodeCreateView, TreeNodeListView, MapCreateWithLayersInlineView, \
    MapUpdateWithLayersInlineView

app_name = 'cbv_trees'
urlpatterns = [
    path('', TemplateView.as_view(template_name='cbv_trees/home.html'), name='home'),
    path('treenode/create', TreeNodeCreateView.as_view(), name='treenode-create'),
    path('treenode/lsit', TreeNodeListView.as_view(), name='treenode-list'),
    path('treenode/formset', TreeNodeFormSetView.as_view(), name='treenode-formset'),

    path('map/list', ListView.as_view(model=Map), name='map-list'),
    path('map/create-with-layers-inline', MapCreateWithLayersInlineView.as_view(),
         name='map-create-with-layers-inline'),
    path('map/<pk>/update-with-layers-inline', MapUpdateWithLayersInlineView.as_view(),
         name='map-update-with-layers-inline'),
]

django_playground/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import path, include

from django_playground.views import HomeView

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('cbv_trees/', include('cbv_trees.urls')),
    path('inline_forms/', include('inline_forms.urls')),
    path('polymorphic_fks/', include('polymorphic_fks.urls')),
    path('admin/', admin.site.urls),
    path('__debug__/', include(debug_toolbar.urls)),
]

inline_forms/urls.py
from django.urls import path

from .views import HomeView, PersonListView, PersonCreateView, PetListView, PetCreateView, PersonWithPetsCreateView, \
    PersonEditAllView, PersonFormSetView, PersonCreateWithPetsInlineView

app_name = 'inline_forms'
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('person/list', PersonListView.as_view(), name='person-list'),
    path('person/create', PersonCreateView.as_view(), name='person-create'),
    path('person/edit-all', PersonEditAllView.as_view(), name='person-edit-all'),
    path('person/formset', PersonFormSetView.as_view(), name='person-formset'),
    path('person/create-with-pets', PersonWithPetsCreateView.as_view(), name='person-create-with-pets'),
    path('person/create-with-pets-inline', PersonCreateWithPetsInlineView.as_view(),
         name='person-create-with-pets-inline'),
    path('pet/list', PetListView.as_view(), name='pet-list'),
    path('pet/create', PetCreateView.as_view(), name='pet-create'),
]

orm_playground/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import path, include

from orm_playground.views import HomeView

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('polymorphic_fks/', include('polymorphic_fks.urls')),
    path('admin/', admin.site.urls),
    path('__debug__/', include(debug_toolbar.urls)),
]

inline_forms/models.py
from django.db import models

# Create your models here.
from django.utils import timezone


class Person(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    created_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"


class Pet(models.Model):
    class Race(models.TextChoices):
        CAT = 'Cat',
        DOG = 'Dog',
        HAMSTER = 'Hamster'

    owner = models.ForeignKey(Person, on_delete=models.CASCADE, blank=False, null=False)
    name = models.CharField(max_length=100, blank=False, null=False)
    race = models.CharField(
        max_length=20,
        choices=Race.choices,
        default=Race.CAT,
        blank=False,
        null=False
    )
    created_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"{self.race} {self.name}"

inline_forms/forms.py
from django.forms import inlineformset_factory, formset_factory, ModelForm
from extra_views import InlineFormSetFactory

from inline_forms.models import Pet, Person


class PersonForm(ModelForm):
    class Meta:
        model = Person
        fields = '__all__'


PersonFormSet = formset_factory(PersonForm, extra=1)
PersonWithPetsFormSet = inlineformset_factory(Person, Pet, fields=('name', 'race', 'created_date',))


class PetInline(InlineFormSetFactory):
    model = Pet
    fields = '__all__'

inline_forms/views.py
# Create your views here.
from django.db import transaction
from django.forms import modelformset_factory
from django.urls import reverse_lazy
from django.views.generic import TemplateView, ListView, CreateView, FormView
from extra_views import ModelFormSetView, CreateWithInlinesView

from inline_forms.forms import PersonWithPetsFormSet, PersonForm, PetInline
from inline_forms.models import Person, Pet


class HomeView(TemplateView):
    template_name = 'inline_forms/home.html'


class PersonListView(ListView):
    model = Person


class PersonCreateView(CreateView):
    model = Person
    # FormMixin requires either 'fields' or 'form_class', but not both
    form_class = PersonForm
    success_url = reverse_lazy('inline_forms:person-list')


# for FormSets, CreateView (or UpdateView) do not really seem to fit, as they are bound to a single object
# so, let's use FormView
class PersonEditAllView(FormView):
    # by using modelformset_factory, '__all__' does include the id field
    form_class = modelformset_factory(Person, fields='__all__', extra=1, can_delete=True)
    success_url = reverse_lazy('inline_forms:person-list')
    template_name = 'inline_forms/person_set_form.html'
    prefix = 'person'

    # FormMixin: Redirects to get_success_url()
    def form_valid(self, form):
        # Changed, deleted, updated instances are bound to the formset automatically
        form.save()
        print(f"Changed: {len(form.changed_objects)}")
        print(f"Deleted: {len(form.deleted_objects)}")
        print(f"Updated: {len(form.new_objects)}")
        # for person_dict in form.cleaned_data:
        #     if person_dict:
        #         # 'id' attribute actually *is* the Person for pre-existing entities
        #         person = person_dict.get('id', None)
        #         del person_dict['id']
        #         if person:
        #             for key in person_dict:
        #                 setattr(person, key, person_dict[key])
        #         else:
        #             person = Person(**person_dict)
        #         person.save()
        return super().form_valid(form)


class PersonFormSetView(ModelFormSetView):
    model = Person
    fields = ['first_name', 'last_name', 'created_date']
    template_name = 'inline_forms/person_formset.html'
    prefix = 'person'
    factory_kwargs = {'extra': 1, 'can_delete': True}


class PersonWithPetsCreateView(CreateView):
    model = Person
    fields = "__all__"
    success_url = reverse_lazy('inline_forms:pet-list')

    def get_context_data(self, **kwargs):
        data = super(PersonWithPetsCreateView, self).get_context_data(**kwargs)
        if self.request.POST:
            data['pets'] = PersonWithPetsFormSet(self.request.POST)
        else:
            data['pets'] = PersonWithPetsFormSet()
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        pets = context['pets']
        with transaction.atomic():
            self.object = form.save()
            if pets.is_valid():
                pets.instance = self.object
                pets.save()
        return super(PersonWithPetsCreateView, self).form_valid(form)


class PersonCreateWithPetsInlineView(CreateWithInlinesView):
    model = Person
    fields = "__all__"
    inlines = [PetInline]
    template_name = 'inline_forms/person_form_inline.html'
    success_url = reverse_lazy('inline_forms:pet-list')


class PetListView(ListView):
    model = Pet


class PetCreateView(CreateView):
    model = Pet
    fields = "__all__"
    success_url = reverse_lazy('inline_forms:pet-list')

inline_forms/templates/inline_forms/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Django Playground: Inline forms</title>
</head>
<body>
<h1>Django Playground: Inline forms</h1>
<h2>Persons</h2>
<ul>
    <li><a href="{% url 'inline_forms:person-list' %}">List Persons</a></li>
    <li><a href="{% url 'inline_forms:person-create' %}">Create Person</a></li>
    <li><a href="{% url 'inline_forms:person-edit-all' %}">Edit/create Persons (FormView)</a></li>
    <li><a href="{% url 'inline_forms:person-formset' %}">Edit/create Persons (ModelFormSetView)</a></li>
    <li><a href="{% url 'inline_forms:person-create-with-pets' %}">Create Person with Pets (CreateView)</a></li>
    <li><a href="{% url 'inline_forms:person-create-with-pets-inline' %}">Create Person with Pets (CreateWithInlinesView)</a>
    </li>
</ul>
<h2>Pets</h2>
<ul>
    <li><a href="{% url 'inline_forms:pet-list' %}">List Pets</a></li>
    <li><a href="{% url 'inline_forms:pet-create' %}">Create Pets</a></li>
</ul>
</body>
</html>

inline_forms/templates/inline_forms/person_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Django Playground: Create a person</title>
</head>
<body>
<h1>Django Playground: Create a person</h1>
</body>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}

    <table>
        {{ pets.management_form }}

        {% for form in pets.forms %}
        {% if forloop.first %}
        <thead>
        <tr>
            {% for field in form.visible_fields %}
            <th>{{ field.label|capfirst }}</th>
            {% endfor %}
        </tr>
        </thead>
        {% endif %}
        <tr class="formset_row">
            {% for field in form.visible_fields %}
            <td>
                {# Include the hidden fields in the form #}
                {% if forloop.first %}
                {% for hidden in form.hidden_fields %}
                {{ hidden }}
                {% endfor %}
                {% endif %}
                {{ field.errors.as_ul }}
                {{ field }}
            </td>
            {% endfor %}
        </tr>
        {% endfor %}
    </table>

    <input type="submit">
</form>
</html>

inline_forms/templates/inline_forms/person_form_inline.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Django Playground: Create a person</title>
</head>
<body>
<h1>Django Playground: Create a person</h1>
</body>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}

    {% for formset in inlines %}
   <table>
        {{ formset.management_form }}

        {% for form in formset.forms %}
        {% if forloop.first %}
        <thead>
        <tr>
            {% for field in form.visible_fields %}
            <th>{{ field.label|capfirst }}</th>
            {% endfor %}
        </tr>
        </thead>
        {% endif %}
        <tr class="{{ formset.prefix }}-form">
            {% for field in form.visible_fields %}
            <td>
                {# Include the hidden fields in the form #}
                {% if forloop.first %}
                {% for hidden in form.hidden_fields %}
                {{ hidden }}
                {% endfor %}
                {% endif %}
                {{ field.errors.as_ul }}
                {{ field }}
            </td>
            {% endfor %}
        </tr>
        {% endfor %}
    </table>
    <button onclick="addForm('{{ formset.prefix }}');return false;">Another field, plz</button>
    {% endfor %}

    <input type="submit">
</form>
<script src="{% static 'inline_forms/js/formset-helper.js' %}"></script>
</html>

inline_forms/templates/inline_forms/person_formset.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Django Playground: Edit persons</title>
</head>
<h1>Django Playground: Edit persons</h1>
<form method="post">
    {% csrf_token %}
    {{ formset.management_form }}
    {% for form in formset %}
    <div class="person-form" {% if forloop.last %}style="display:none" {% endif %}>
        {{ form.as_p }}
    </div>
    {% endfor %}
    <button onclick="addForm('person');return false;">Gimme another field</button>
    <input type="submit">
</form>
<script src="{% static 'inline_forms/js/formset-helper.js' %}"></script>
</body>
</html>

inline_forms/templates/inline_forms/person_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Django Playground: List persons</title>
</head>
<body>
<h1>Django Playground: List persons</h1>
<h1>Persons</h1>
<ul>
{% for person in object_list %}
    <li>{{ person.last_name }}, {{ person.first_name }}</li>
{% empty %}
    <li>No persons yet.</li>
{% endfor %}
</ul>
</body>
</html>

inline_forms/templates/inline_forms/person_set_form.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Django Playground: Edit persons</title>
</head>
<h1>Django Playground: Edit persons</h1>
<form method="post">
    {% csrf_token %}
    {{ form.management_form }}
    {% for form in form %}
    <div class="person-form" {% if forloop.last %}style="display:none" {% endif %}>
        {{ form.as_p }}
    </div>
    {% endfor %}
    <button onclick="addForm('person');return false;">Gimme another field</button>
    <input type="submit">
</form>
<script src="{% static 'inline_forms/js/formset-helper.js' %}"></script>
</body>
</html>

inline_forms/templates/inline_forms/pet_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Django Playground: Create a pet</title>
</head>
<body>
<h1>Django Playground: Create a pet</h1>
</body>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit">
</form>
</html>

inline_forms/templates/inline_forms/pet_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Django Playground: List pets</title>
</head>
<body>
<h1>Django Playground: List pets</h1>
<h1>Pets</h1>
<ul>
{% for pet in object_list %}
    <li>{{ pet.name }}, {{ pet.race }}</li>
{% empty %}
    <li>No pets yet.</li>
{% endfor %}
</ul>
</body>
</html>