cbv_trees/urls.py
from django.urls import path
from django.views.generic import TemplateView, ListView

from cbv_trees.models import Map
from cbv_trees.views import TreeNodeFormSetView, TreeNodeCreateView, TreeNodeListView, MapCreateWithLayersInlineView, \
    MapUpdateWithLayersInlineView

app_name = 'cbv_trees'
urlpatterns = [
    path('', TemplateView.as_view(template_name='cbv_trees/home.html'), name='home'),
    path('treenode/create', TreeNodeCreateView.as_view(), name='treenode-create'),
    path('treenode/lsit', TreeNodeListView.as_view(), name='treenode-list'),
    path('treenode/formset', TreeNodeFormSetView.as_view(), name='treenode-formset'),

    path('map/list', ListView.as_view(model=Map), name='map-list'),
    path('map/create-with-layers-inline', MapCreateWithLayersInlineView.as_view(),
         name='map-create-with-layers-inline'),
    path('map/<pk>/update-with-layers-inline', MapUpdateWithLayersInlineView.as_view(),
         name='map-update-with-layers-inline'),
]

django_playground/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import path, include

from django_playground.views import HomeView

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('cbv_trees/', include('cbv_trees.urls')),
    path('inline_forms/', include('inline_forms.urls')),
    path('polymorphic_fks/', include('polymorphic_fks.urls')),
    path('admin/', admin.site.urls),
    path('__debug__/', include(debug_toolbar.urls)),
]

orm_playground/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import path, include

from orm_playground.views import HomeView

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('polymorphic_fks/', include('polymorphic_fks.urls')),
    path('admin/', admin.site.urls),
    path('__debug__/', include(debug_toolbar.urls)),
]

polymorphic_fks/urls.py
from django.urls import path

from .views import HomeView, CheckrunsWithGenericFk, CheckrunsWithMultipleFks, \
    CheckrunsWithFksInChildTables, CheckrunsWithDjangoPolymorphic, OgcServiceDetailView, LayerDetailView, \
    FeatureTypeDetailView, DatasetMetadataDetailView, ServiceMetadataDetailView, LayerMetadataDetailView, \
    FeatureTypeMetadataDetailView, CheckrunsWithFkLookupTable

app_name = 'polymorphic_fks'
urlpatterns = [
    path('', HomeView.as_view(), name='home'),

    # resources
    path('ogcservice/<pk>', OgcServiceDetailView.as_view(), name='ogcservice-detail'),
    path('layer/<pk>', LayerDetailView.as_view(), name='layer-detail'),
    path('featuretype/<pk>', FeatureTypeDetailView.as_view(), name='featuretype-detail'),
    path('dataset-metadata/<pk>', DatasetMetadataDetailView.as_view(), name='dataset-metadata-detail'),
    path('service-metadata/<pk>', ServiceMetadataDetailView.as_view(), name='service-metadata-detail'),
    path('layer-metadata/<pk>', LayerMetadataDetailView.as_view(), name='layer-metadata-detail'),
    path('featuretype-metadata/<pk>', FeatureTypeMetadataDetailView.as_view(), name='featuretype-metadata-detail'),

    # references
    path('checkruns-with-generic-fk/', CheckrunsWithGenericFk.as_view(), name='checkruns-with-generic-fk'),
    path('checkruns-with-multiple-fks/', CheckrunsWithMultipleFks.as_view(), name='checkruns-with-multiple-fks'),
    path('checkruns-with-fk-lookup-table/', CheckrunsWithFkLookupTable.as_view(),
         name='checkruns-with-fk-lookup-table'),
    path('checkruns-with-fks-in-child-tables/', CheckrunsWithFksInChildTables.as_view(),
         name='checkruns-with-fks-in-child-table'),
    path('checkruns-with-django-polymorphic/', CheckrunsWithDjangoPolymorphic.as_view(),
         name='checkruns-with-django-polymorphic'),
]

polymorphic_fks/models/fruits.py
import random
from random import randint

from django.db import models


class Apple(models.Model):
    class AppleColor(models.TextChoices):
        RED = 'red',
        GOLDEN = 'golden',
        GREEN = 'green',
        YELLOW = 'yellow'

    color = models.TextField(blank=False, null=False)

    def __str__(self):
        return f'an apple: color={self.color}'

    @staticmethod
    def random():
        return Apple(color=random.choice(list(Apple.AppleColor)))


class Banana(models.Model):
    length_cm = models.DecimalField(max_digits=4, decimal_places=2)

    def __str__(self):
        return f'a banana: length={self.length_cm} cm'

    @staticmethod
    def random():
        return Banana(length_cm=random.random() * 25 + 5)


class Grapes(models.Model):
    count = models.IntegerField()

    def __str__(self):
        return f'some grapes: count={self.count}'

    @staticmethod
    def random():
        return Grapes(count=randint(5, 50))


class Kiwifruit(models.Model):
    weight_g = models.DecimalField(max_digits=5, decimal_places=2)

    def __str__(self):
        return f'a kiwi fruit: weight={self.weight_g}g'

    @staticmethod
    def random():
        return Kiwifruit(weight_g=random.random() * 190 + 10)


class Lemon(models.Model):
    circumference_mm = models.DecimalField(max_digits=5, decimal_places=2)

    def __str__(self):
        return f'a lemon: circumference_mm={self.circumference_mm}mm'

    @staticmethod
    def random():
        return Lemon(circumference_mm=random.random() * 150 + 50)


class Pineapple(models.Model):
    height_cm = models.DecimalField(max_digits=4, decimal_places=2)
    weight_kg = models.DecimalField(max_digits=4, decimal_places=3)

    def __str__(self):
        return f'a pineapple: height_cm={self.height_cm}, weight_kg={self.weight_kg}'

    @staticmethod
    def random():
        return Pineapple(height_cm=random.random() * 30 + 10, weight_kg=random.random() * 2.5 + 0.5)


class Watermelon(models.Model):
    circumference_cm = models.DecimalField(max_digits=4, decimal_places=2)
    weight_kg = models.DecimalField(max_digits=5, decimal_places=3)

    def __str__(self):
        return f'a watermelon: circumference_cm={self.circumference_cm}, weight_kg={self.weight_kg}'

    @staticmethod
    def random():
        return Watermelon(circumference_cm=random.random() * 40 + 20, weight_kg=random.random() * 14 + 1)

polymorphic_fks/models/qc.py
from django.db import models


class QualityControl(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

polymorphic_fks/views.py
# Create your views here.
from django.views.generic import TemplateView, DetailView
from django_tables2 import SingleTableView, RequestConfig

from polymorphic_fks.models import CheckrunWithGenericFk, CheckrunWithMultipleFks, \
    MultiTableBaseCheckrun, DjangoPolymorphicBaseCheckrun, OgcService, Layer, FeatureType, ServiceMetadata, \
    LayerMetadata, FeatureTypeMetadata, DatasetMetadata, CheckrunWithFkLookupTable
from polymorphic_fks.tables import \
    CheckrunWithMultipleFksTable, MultiTableBaseCheckrunTable, DjangoPolymorphicBaseCheckrunTable, \
    CheckrunWithGenericFkTable, CheckrunWithFkLookupTableTable


class HomeView(TemplateView):
    template_name = 'polymorphic_fks/home.html'


class OgcServiceDetailView(DetailView):
    model = OgcService


class LayerDetailView(DetailView):
    model = Layer


class FeatureTypeDetailView(DetailView):
    model = FeatureType


class DatasetMetadataDetailView(DetailView):
    model = DatasetMetadata


class ServiceMetadataDetailView(DetailView):
    model = ServiceMetadata


class LayerMetadataDetailView(DetailView):
    model = LayerMetadata


class FeatureTypeMetadataDetailView(DetailView):
    model = FeatureTypeMetadata


class CheckrunsWithGenericFk(SingleTableView):
    model = CheckrunWithGenericFk
    table_class = CheckrunWithGenericFkTable
    template_name = 'polymorphic_fks/checkruns.html'

    def get_queryset(self):
        qs = super().get_queryset().order_by('pk')
        return qs.select_related('_resource_type')

    def get_table(self, **kwargs):
        """
        Return a table object to use. The table has automatic support for
        sorting and pagination.
        """
        table_class = self.get_table_class()
        table = table_class(data=self.get_table_data(), **kwargs)
        table.exclude = tuple(self.request.GET.get('exclude', '').split(','))
        return RequestConfig(self.request, paginate=self.get_table_pagination(table)).configure(
            table
        )


class CheckrunsWithMultipleFks(SingleTableView):
    model = CheckrunWithMultipleFks
    table_class = CheckrunWithMultipleFksTable
    template_name = 'polymorphic_fks/checkruns.html'

    def get_queryset(self):
        qs = super().get_queryset().order_by('pk')
        return qs.select_related('ogc_service', 'layer', 'feature_type', 'dataset_metadata', 'service_metadata',
                                 'layer_metadata', 'feature_type_metadata')

    def get_table(self, **kwargs):
        """
        Return a table object to use. The table has automatic support for
        sorting and pagination.
        """
        table_class = self.get_table_class()
        table = table_class(data=self.get_table_data(), **kwargs)
        table.exclude = tuple(self.request.GET.get('exclude', '').split(','))
        return RequestConfig(self.request, paginate=self.get_table_pagination(table)).configure(
            table
        )


class CheckrunsWithFkLookupTable(SingleTableView):
    model = CheckrunWithFkLookupTable
    table_class = CheckrunWithFkLookupTableTable
    template_name = 'polymorphic_fks/checkruns.html'

    def get_queryset(self):
        qs = super().get_queryset().order_by('pk')
        return qs.select_related('_resource__ogc_service', '_resource__layer', '_resource__feature_type',
                                 '_resource__dataset_metadata', '_resource__service_metadata',
                                 '_resource__layer_metadata', '_resource__feature_type_metadata')

    def get_table(self, **kwargs):
        """
        Return a table object to use. The table has automatic support for
        sorting and pagination.
        """
        table_class = self.get_table_class()
        table = table_class(data=self.get_table_data(), **kwargs)
        table.exclude = tuple(self.request.GET.get('exclude', '').split(','))
        return RequestConfig(self.request, paginate=self.get_table_pagination(table)).configure(
            table
        )


class CheckrunsWithFksInChildTables(SingleTableView):
    model = MultiTableBaseCheckrun
    table_class = MultiTableBaseCheckrunTable
    template_name = 'polymorphic_fks/checkruns.html'

    def get_queryset(self):
        qs = super().get_queryset().order_by('pk')
        return qs.select_related('multitablecheckrunogcservice__resource', 'multitablecheckrunlayer__resource',
                                 'multitablecheckrunfeaturetype__resource',
                                 'multitablecheckrundatasetmetadata__resource',
                                 'multitablecheckrunservicemetadata__resource',
                                 'multitablecheckrunlayermetadata__resource',
                                 'multitablecheckrunfeaturetypemetadata__resource')

    def get_table(self, **kwargs):
        """
        Return a table object to use. The table has automatic support for
        sorting and pagination.
        """
        table_class = self.get_table_class()
        table = table_class(data=self.get_table_data(), **kwargs)
        table.exclude = tuple(self.request.GET.get('exclude', '').split(','))
        return RequestConfig(self.request, paginate=self.get_table_pagination(table)).configure(
            table
        )


class CheckrunsWithDjangoPolymorphic(SingleTableView):
    model = DjangoPolymorphicBaseCheckrun
    table_class = DjangoPolymorphicBaseCheckrunTable
    template_name = 'polymorphic_fks/checkruns.html'

    def get_queryset(self):
        qs = super().get_queryset().order_by('pk')
        return qs
        # select_related on inherited models is not supported yet...
        # return qs.select_related('djangopolymorphiccheckrunogcservice', 'djangopolymorphiccheckrunlayer', ...)
        # see https://django-polymorphic.readthedocs.io/en/stable/advanced.html#combining-querysets
        # only works when one turns of the polymorphic mode:
        # return qs.non_polymorphic().select_related('djangopolymorphiccheckrunogcservice',
        #                                            'djangopolymorphiccheckrunlayer')

    def get_table(self, **kwargs):
        """
        Return a table object to use. The table has automatic support for
        sorting and pagination.
        """
        table_class = self.get_table_class()
        table = table_class(data=self.get_table_data(), **kwargs)
        table.exclude = tuple(self.request.GET.get('exclude', '').split(','))
        return RequestConfig(self.request, paginate=self.get_table_pagination(table)).configure(
            table
        )

polymorphic_fks/templates/polymorphic_fks/checkruns.html
{% load render_table from django_tables2 %}
<!doctype html>
<html>
    <head>
        <title>List of Checkruns</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
    </head>
    <body>
        {% render_table table %}
    </body>
</html>

polymorphic_fks/templates/polymorphic_fks/datasetmetadata_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Dataset Metadata {{ object.pk }}</title>
</head>
<body>
<h1>Dataset Metadata {{ object.pk }}</h1>
<p>File identifier: {{ object.file_identifier }}</p>
<h2>Layers</h2>
<ul>
{% for layer in object.layers.all %}
<li><a href="{% url 'polymorphic_fks:layer-detail' layer.pk %}">{{ layer.name }}</a></li>
{% endfor %}
</ul>
<h2>Feature types</h2>
<ul>
{% for feature_type in object.feature_types.all %}
<li><a href="{% url 'polymorphic_fks:featuretype-detail' feature_type.pk %}">{{ feature_type.name }}</a></li>
{% endfor %}
</ul>
</body>
</html>

polymorphic_fks/templates/polymorphic_fks/featuretype_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Feature Type {{ object.pk }}</title>
</head>
<body>
<h1>Feature Type {{ object.pk }}</h1>
<p>Name: {{ object.name }}</p>
<p>Service: <a href="{% url 'polymorphic_fks:ogcservice-detail' object.service_id %}">{{ object.service_id }}</a></p>
</body>
</html>

polymorphic_fks/templates/polymorphic_fks/featuretypemetadata_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Feature Type Metadata {{ object.pk }}</title>
</head>
<body>
<h1>Feature Type Metadata {{ object.pk }}</h1>
<p>File identifier: {{ object.file_identifier }}</p>
<p>Feature Type: <a href="{% url 'polymorphic_fks:featuretype-detail' object.feature_type_id %}">{{ object.feature_type_id }}</a></p>
</body>
</html>

polymorphic_fks/templates/polymorphic_fks/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Django ORM Playground: Polymorphic FKs</title>
</head>
<body>
<h1>Django ORM Playground: Polymorphic FKs</h1>
<h2>Performance optimization: List View with link to related object</h2>
<ul>
    <li><a href="{% url 'polymorphic_fks:checkruns-with-generic-fk' %}?exclude=resource_name">Generic FK</a></li>
    <li><a href="{% url 'polymorphic_fks:checkruns-with-multiple-fks' %}?exclude=resource_name">Sparse multi FKs (one FK for each resource type)</a></li>
    <li><a href="{% url 'polymorphic_fks:checkruns-with-fk-lookup-table' %}?exclude=resource_name">Sparse intermediate FK lookup table (one FK for each resource type)</a></li>
    <li><a href="{% url 'polymorphic_fks:checkruns-with-fks-in-child-table' %}?exclude=resource_name">Multi-table inheritance (simple FK in each child table)</a></li>
    <li><a href="{% url 'polymorphic_fks:checkruns-with-django-polymorphic' %}?exclude=resource_name">Multi-table inheritance with django-polymorphic</a></li>
</ul>
<h2>Performance optimization: List View with link to related object + additional object attributes (name)</h2>
<ul>

    <li><a href="{% url 'polymorphic_fks:checkruns-with-generic-fk' %}">Generic FK</a></li>
    <li><a href="{% url 'polymorphic_fks:checkruns-with-multiple-fks' %}">Sparse multi FKs (one FK for each resource type)</a></li>
    <li><a href="{% url 'polymorphic_fks:checkruns-with-fk-lookup-table' %}">Sparse intermediate FK lookup table (one FK for each resource type)</a></li>
    <li><a href="{% url 'polymorphic_fks:checkruns-with-fks-in-child-table' %}">Multi-table inheritance (simple FK in each child table)</a></li>
    <li><a href="{% url 'polymorphic_fks:checkruns-with-django-polymorphic' %}">Multi-table inheritance with django-polymorphic</a></li>

</ul>
</body>
</html>

polymorphic_fks/templates/polymorphic_fks/layer_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Layer {{ object.pk }}</title>
</head>
<body>
<h1>Layer {{ object.pk }}</h1>
<p>Name: {{ object.name }}</p>
<p>Service: <a href="{% url 'polymorphic_fks:ogcservice-detail' object.service_id %}">{{ object.service_id }}</a></p>
</body>
</html>

polymorphic_fks/templates/polymorphic_fks/layermetadata_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Layer Metadata {{ object.pk }}</title>
</head>
<body>
<h1>Layer Metadata {{ object.pk }}</h1>
<p>File identifier: {{ object.file_identifier }}</p>
<p>Layer: <a href="{% url 'polymorphic_fks:layer-detail' object.layer_id %}">{{ object.layer_id }}</a></p>
</body>
</html>

polymorphic_fks/templates/polymorphic_fks/ogcservice_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>OgcService {{ object.pk }}</title>
</head>
<body>
<h1>OgcService {{ object.pk }}</h1>
<p>Type: {{ object.service_type }}</p>
<p>Origin URL: {{ object.origin_url }}</p>
<p>Name: {{ object.name }}</p>
</body>
</html>

polymorphic_fks/templates/polymorphic_fks/servicemetadata_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Service Metadata {{ object.pk }}</title>
</head>
<body>
<h1>Service Metadata {{ object.pk }}</h1>
<p>File identifier: {{ object.file_identifier }}</p>
<p>Service: <a href="{% url 'polymorphic_fks:ogcservice-detail' object.service_id %}">{{ object.service_id }}</a></p>
</body>
</html>