cbv_trees/urls.py
from django.urls import path
from django.views.generic import TemplateView, ListView

from cbv_trees.models import Map
from cbv_trees.views import TreeNodeFormSetView, TreeNodeCreateView, TreeNodeListView, MapCreateWithLayersInlineView, \
    MapUpdateWithLayersInlineView

app_name = 'cbv_trees'
urlpatterns = [
    path('', TemplateView.as_view(template_name='cbv_trees/home.html'), name='home'),
    path('treenode/create', TreeNodeCreateView.as_view(), name='treenode-create'),
    path('treenode/lsit', TreeNodeListView.as_view(), name='treenode-list'),
    path('treenode/formset', TreeNodeFormSetView.as_view(), name='treenode-formset'),

    path('map/list', ListView.as_view(model=Map), name='map-list'),
    path('map/create-with-layers-inline', MapCreateWithLayersInlineView.as_view(),
         name='map-create-with-layers-inline'),
    path('map/<pk>/update-with-layers-inline', MapUpdateWithLayersInlineView.as_view(),
         name='map-update-with-layers-inline'),
]

django_playground/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import path, include

from django_playground.views import HomeView

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('cbv_trees/', include('cbv_trees.urls')),
    path('inline_forms/', include('inline_forms.urls')),
    path('polymorphic_fks/', include('polymorphic_fks.urls')),
    path('admin/', admin.site.urls),
    path('__debug__/', include(debug_toolbar.urls)),
]

orm_playground/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import path, include

from orm_playground.views import HomeView

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('polymorphic_fks/', include('polymorphic_fks.urls')),
    path('admin/', admin.site.urls),
    path('__debug__/', include(debug_toolbar.urls)),
]

cbv_trees/models.py
from django.db import models

# Create your models here.
from extra_views import InlineFormSetFactory
from mptt.fields import TreeForeignKey
from mptt.models import MPTTModel


class TreeNode(MPTTModel):
    parent = TreeForeignKey("TreeNode", on_delete=models.CASCADE, null=True, blank=True,
                            related_name="child_nodes")
    name = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.name}"


class Map(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.name}"


class Layer(MPTTModel):
    map = models.ForeignKey(Map, on_delete=models.CASCADE, blank=False, null=False)
    parent = TreeForeignKey("Layer", on_delete=models.CASCADE, null=True, blank=True,
                            related_name="child_layers")
    name = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.name}"

cbv_trees/forms.py
from django import forms
from django.forms import ModelForm, BaseModelFormSet, BaseInlineFormSet, CharField, IntegerField, Textarea, NumberInput, \
    TextInput
from extra_views import InlineFormSetFactory

from cbv_trees.models import TreeNode, Layer


class TreeNodeForm(ModelForm):
    parent_form_id = forms.CharField(max_length=20, required=False)

    class Meta:
        model = TreeNode
        fields = ['id', 'parent', 'name']


class BaseModelTreeFormSet(BaseModelFormSet):

    def save(self, commit=True):
        """
        Save model instances for every form, adding and changing instances
        as necessary, and return the list of instances.
        """

        # delete all forms that existed before
        for form in self.forms:
            existing_object = form.cleaned_data.get('id', None)
            if existing_object:
                print(f"Deleting... {existing_object}")
                existing_object.delete()

        # save all forms not marked for deletion
        new_objects = []

        # ignore the last form (this is the template form)
        total_forms = self.management_form.cleaned_data['TOTAL_FORMS'] - 1
        for i in range(0, total_forms):
            form = self.forms[i]
            print(f"Saving form {i}: {form}")
            if form.cleaned_data.get('DELETE', None):
                continue
            parent_form_id = form.cleaned_data.get("parent_form_id", None)
            if parent_form_id:
                parent = new_objects[int(parent_form_id)]
                form.instance.parent = parent
            else:
                form.instance.parent = None
            form.cleaned_data['id'] = None

            model_instance = form.save(commit=False)
            # ensure that there are no left-over values for MPTT-specific fields (lft, rght, tree_id, level)
            clean_model_instance = TreeNode(name=model_instance.name, parent=model_instance.parent)
            clean_model_instance.save()
            new_objects.append(clean_model_instance)
            print(f"Saved {clean_model_instance}")
        return new_objects


class LayerForm(ModelForm):
    parent_form_idx = forms.CharField(max_length=20, required=False)

    class Meta:
        model = Layer
        widgets = {
            'id': TextInput(),
            'parent': TextInput()
        }
        fields = ['id', 'parent', 'parent_form_idx', 'name']


class LayerTreeInlineFormSet(BaseInlineFormSet):

    # TODO handle re-ordering of siblings

    def save_new(self, form, commit=True):
        """Save and return a new model instance for the given form."""
        parent_form_idx = form.cleaned_data.get("parent_form_idx", None)
        if parent_form_idx and form.instance.parent is None:
            parent = self.forms[int(parent_form_idx)].instance
            form.instance.parent = parent
        return form.save(commit=commit)

    def save_existing(self, form, instance, commit=True):
        """Save and return an existing model instance for the given form."""
        parent_form_idx = form.cleaned_data.get("parent_form_idx", None)
        if parent_form_idx and form.instance.parent is None:
            parent = self.forms[int(parent_form_idx)].instance
            form.instance.parent = parent
        return form.save(commit=commit)

    def save(self, commit=True):
        """
        Save model instances for every form, adding and changing instances
        as necessary, and return the list of instances.
        """
        super().save(commit)
        return

        # delete all forms that existed before
        # TODO better delete all objects related to the "instance"?
        for form in self.forms:
            existing_object = form.cleaned_data.get('id', None)
            if existing_object:
                print(f"Deleting... {existing_object}")
                existing_object.delete()

        new_objects = []
        # ignore the last form (this is the template form)
        total_forms = self.management_form.cleaned_data['TOTAL_FORMS'] - 1
        for i in range(0, total_forms):
            form = self.forms[i]
            if form.cleaned_data.get('DELETE', None):
                continue
            parent_form_idx = form.cleaned_data.get("parent_form_idx", None)
            if parent_form_idx:
                parent = new_objects[int(parent_form_idx)]
                form.instance.parent = parent
            else:
                form.instance.parent = None
            model_instance = form.save(commit=False)
            # ensure that there are no left-over values for MPTT-specific fields (lft, rght, tree_id, level)
            clean_model_instance = Layer(name=model_instance.name, map=model_instance.map, parent=model_instance.parent)
            clean_model_instance.save()
            new_objects.append(clean_model_instance)
            print(f"Saved {clean_model_instance}")
        return new_objects


class LayerInline(InlineFormSetFactory):
    model = Layer
    # fields = '__all__'
    form_class = LayerForm
    prefix = 'layer'
    factory_kwargs = {'extra': 1, 'can_delete': True, 'formset': LayerTreeInlineFormSet}

cbv_trees/views.py
# Create your views here.
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView
from extra_views import ModelFormSetView, CreateWithInlinesView, UpdateWithInlinesView

from cbv_trees.forms import TreeNodeForm, BaseModelTreeFormSet, LayerInline
from cbv_trees.models import TreeNode, Map


class TreeNodeCreateView(CreateView):
    model = TreeNode
    # FormMixin requires either 'fields' or 'form_class', but not both
    form_class = TreeNodeForm
    success_url = reverse_lazy('cbv_trees:treenode-list')


class TreeNodeListView(ListView):
    model = TreeNode


class TreeNodeFormSetView(ModelFormSetView):
    model = TreeNode
    form_class = TreeNodeForm
    template_name = 'cbv_trees/treenode_formset.html'
    prefix = 'treenode'
    factory_kwargs = {'extra': 1, 'can_delete': True, 'formset': BaseModelTreeFormSet}


class MapCreateWithLayersInlineView(CreateWithInlinesView):
    model = Map
    fields = "__all__"
    inlines = [LayerInline]
    template_name = 'cbv_trees/map_form_inline.html'
    success_url = reverse_lazy('cbv_trees:map-list')


class MapUpdateWithLayersInlineView(UpdateWithInlinesView):
    model = Map
    fields = "__all__"
    inlines = [LayerInline]
    template_name = 'cbv_trees/map_form_inline.html'
    success_url = reverse_lazy('cbv_trees:map-list')

    def get_initial(self):
        initial = super().get_initial()
        return initial

cbv_trees/templates/cbv_trees/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Django Playground: Tree formsets & views</title>
</head>
<body>
<h1>Django Playground: Tree formsets & views</h1>
<ul>
    <li><a href="{% url 'cbv_trees:treenode-create' %}">Create TreeNode</a></li>
    <li><a href="{% url 'cbv_trees:treenode-list' %}">List TreeNodes</a></li>
    <li><a href="{% url 'cbv_trees:treenode-formset' %}">Edit/create TreeNodes (ModelFormSetView)</a></li>
</ul>
<h2>Maps and Layers</h2>
<ul>
    <li><a href="{% url 'cbv_trees:map-list' %}">List Maps</a></li>
    <li><a href="{% url 'cbv_trees:map-create-with-layers-inline' %}">Create Map with Layers (CreateViewInlines)</a></li>
</ul>
</body>
</html>

cbv_trees/templates/cbv_trees/map_form_inline.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Django Playground: Create a map</title>
</head>
<body>
<h1>Django Playground: Create a map</h1>
</body>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}

    {% for formset in inlines %}
    <h2>Layers</h2>
    <h3>Layer Tree</h3>

    <div id="mapcontext_tree"
         style="border: 1px solid #ced4da; border-radius: .25rem; padding: .375rem .75rem"
         class="form-group">
    </div>

    <h3>Layer Formset</h3>
    <table>
        {{ formset.management_form }}

        {% for form in formset.forms %}
        {% if forloop.first %}
        <thead>
        <tr>
            {% for field in form.visible_fields %}
            <th>{{ field.label|capfirst }}</th>
            {% endfor %}
        </tr>
        </thead>
        <tbody id="{{ formset.prefix }}-forms">
        {% endif %}
        <tr class="{{ formset.prefix }}-form">
            {% for field in form.visible_fields %}
            <td>
                {# Include the hidden fields in the form #}
                {% if forloop.first %}
                {% for hidden in form.hidden_fields %}
                {{ hidden }}
                {% endfor %}
                {% endif %}
                {{ field.errors.as_ul }}
                {{ field }}
            </td>
            {% endfor %}
        </tr>
        {% endfor %}
        </tbody>
    </table>
    {% endfor %}

    <input type="submit">
</form>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jstree/3.3.11/themes/default/style.min.css"
      integrity="sha512-P8BwDSUInKMA7I116Z1RFg/Dfk85uFdliEUYO7vQlwtxLVMNvZimfMAQsaf++9EhlAGOVX6yhDQAIY3/70jDUg=="
      crossorigin="anonymous" referrerpolicy="no-referrer"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"
      integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ=="
      crossorigin="anonymous" referrerpolicy="no-referrer"/>
<link rel="stylesheet" type="text/css" href="{% static '/cbv_trees/css/folder-style.css' %}" media="all"/>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"
        integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jstree/3.3.11/jstree.min.js"
        integrity="sha512-bU6dl4fd2XN3Do3aWypPP2DcKywDyR3YlyszV+rOw9OpglrGyBs6TyTsbglf9umgE+sy+dKm1UHhi07Lv+Vtfg=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://cdn.jsdelivr.net/npm/jstree-actions@0.2.1/jstree-actions.min.js"
        integrity="sha256-9UEvBZl2CzCWCSvHfT1PKY7xfkJBJmRuNeCaUhS66IE=" crossorigin="anonymous"></script>

<script type="text/javascript" src="{% static '/cbv_trees/js/treeformset-helper.js' %}"></script>
<script>
    initJsTreeFormset('#mapcontext_tree', 'layer', 'parent', 'name', true);
</script>

</html>

cbv_trees/templates/cbv_trees/map_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Django Playground: List maps</title>
</head>
<body>
<h1>Django Playground: List maps</h1>
<h1>Maps</h1>
<ul>
    {% for map in object_list %}
    <li>{{ map.name }} #layers: {{ map.layer_set.all | length }} <a
            href="{% url 'cbv_trees:map-update-with-layers-inline' map.pk %}">Update (with layers)</a></li>
    {% empty %}
    <li>No maps yet.</li>
    {% endfor %}
</ul>
</body>
</html>

cbv_trees/templates/cbv_trees/treenode_form.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Django Playground: Create a treenode</title>
</head>
<body>
<h1>Django Playground: Create a treenode</h1>
</body>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit">
</form>
</html>

cbv_trees/templates/cbv_trees/treenode_formset.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Django Playground: Edit tree nodes</title>
</head>
<h1>Django Playground: Edit tree nodes</h1>
<form method="post">
    {% csrf_token %}
    {{ formset.management_form }}
    {% for form in formset %}
    <div class="treenode-form" {% if forloop.last %}style="display:none" {% endif %}>
        {{ form.as_p }}
    </div>
    {% endfor %}
    <button onclick="addForm('treenode');return false;">Gimme another node</button>
    <input type="submit">
</form>
<script src="{% static 'inline_forms/js/formset-helper.js' %}"></script>
</body>
</html>

cbv_trees/templates/cbv_trees/treenode_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Django Playground: List tree nodes</title>
</head>
<body>
<h1>Django Playground: List tree nodes</h1>
<h1>Persons</h1>
<ul>
{% for treenode in object_list %}
    <li>{{ treenode.name }}, parent: {{ treenode.parent }}</li>
{% empty %}
    <li>No tree nodes yet.</li>
{% endfor %}
</ul>
</body>
</html>